name: Sync to Clone Repo

on:
  push:
    branches:
      - main

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Original Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Clone Repo
        run: |
          git remote add clone https://${{ secrets.SYNC_TOKEN }}@://github.com
          git push clone main --force
